server.port=8080
spring.application.name=Healthcare Login System

# Thymeleaf settings
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML

# Enable static resources
spring.web.resources.static-locations=classpath:/static/
